### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Merovius** [keybase/go-client#24]
# github.com/keybase/go-client
./cmd_db_nuke.go:56: unknown cli.Command field 'Subcommands' in struct literal
./cmd_mykey.go:98: unknown cli.Command field 'Subcommands' in struct literal
./cmd_prove.go:57: cannot use SecretUIServer literal (type *SecretUIServer) as type keybase_1.SecretUiInterface in argument to keybase_1.SecretUiProtocol:
	*SecretUIServer does not implement keybase_1.SecretUiInterface (missing GetKeybasePassphrase method)
./cmd_sigs_list.go:324: unknown cli.Command field 'Subcommands' in struct literal
./markup.go:213: cannot use doc.Selection.Nodes (type []*"code.google.com/p/go.net/html".Node) as type []*"golang.org/x/net/html".Node in argument to renderer.RenderNodes

**Comment by maxtaco** [comment]
work in progress, builds are not yet promised.
